language: java
os: linux
jdk: openjdk11

before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.7/protoc-3.15.7-linux-x86_64.zip
  - unzip -qq protoc-3.15.7-linux-x86_64.zip
  - export PATH=bin:$PATH
  - wget https://services.gradle.org/distributions/gradle-6.8.1-bin.zip
  - unzip -qq gradle-6.8.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.8.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
