language: java
os: linux
jdk: openjdk11

before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip
  - unzip -qq protoc-3.19.1-linux-x86_64.zip
  - export PATH=bin:$PATH
  - wget https://services.gradle.org/distributions/gradle-7.3.1-bin.zip
  - unzip -qq gradle-7.3.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.3.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
