# from https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml
name: Java CI with Gradle
on: [workflow_dispatch, push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:7-jdk11
    steps:
    - uses: actions/checkout@v3
    - name: Build with Gradle
      run: gradle build
