# from https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml
name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8-jdk11
    steps:
    - uses: actions/checkout@v3
    - name: Build with Gradle
      run: gradle build
